app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FileField, SelectField, SubmitField
from wtforms.validators import DataRequired
from flask_wtf.file import FileAllowed, FileRequired

class CodeSnippetForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    code = TextAreaField('Code', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    language = SelectField('Language', choices=[('python', 'Python'), ('chimera', 'Chimera'), ('excel', 'Excel'), ('imagej', 'ImageJ')], validators=[DataRequired()])
    submit = SubmitField('Submit')

class CodeFileForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    file = FileField('Code File', validators=[FileRequired(), FileAllowed(['py', 'ipynb', 'xls', 'ijm'], 'Code files only!')])
    language = SelectField('Language', choices=[('python', 'Python'), ('chimera', 'Chimera'), ('excel', 'Excel'), ('imagej', 'ImageJ')], validators=[DataRequired()])
    submit = SubmitField('Submit')

class BlogPostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    post = TextAreaField('Post', validators=[DataRequired()])
    image = FileField('Image', validators=[FileAllowed(['jpg', 'png'], 'Images only!')])
    submit = SubmitField('Submit')

class SearchForm(FlaskForm):
    keywords = StringField('Keywords', validators=[DataRequired()])
    submit = SubmitField('Search')

class CodeFileForms(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    code = FileField('Code', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired()])
    language = SelectField('Language', choices=[('python', 'Python'), ('chimera', 'Chimera'), ('excel', 'Excel'), ('imagej', 'ImageJ')], validators=[DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from config import Config
from .views import main  # Import the blueprint
import os 

def create_app():
    app = Flask(__name__)
    app.register_blueprint(main)
    app.config.from_object(Config)
    app.config['UPLOAD_FOLDER'] = os.path.dirname(os.path.abspath(__file__)) + '/uploads/'
    return app

app/views.py
from flask import render_template, redirect, url_for, Blueprint
from werkzeug.utils import secure_filename
from flask import request, current_app as app
from .forms import CodeSnippetForm, CodeFileForm, BlogPostForm
from .scripts.create_markdown import create_markdown
from .scripts.commit_to_git import commit_to_git
from .scripts.search_files import search_matching_files
import os
import fnmatch

main = Blueprint('main', __name__)

@main.route('/')
def index():
    return render_template('index.html')

@main.route('/share_code', methods=['GET', 'POST'])
def share_code():
    return render_template('share_code.html')

@main.route('/share_code_snippet', methods=['GET', 'POST'])
def share_code_snippet():
    form = CodeSnippetForm()
    if form.validate_on_submit():
        markdown_path = create_markdown(form.data, 'snippet')
        commit_to_git(form.data, markdown_path, 'snippet')
        return redirect(url_for('main.index'))
    return render_template('share_code_snippet.html', form=form)

@main.route('/share_code_file', methods=['GET', 'POST'])
def share_code_file():
    form = CodeFileForm()
    if form.validate_on_submit():
        filename = secure_filename(form.file.data.filename)
        file_path = os.path.join(app.config['UPLOAD_FOLDER'], filename)
        form.file.data.save(file_path)
        markdown_path = create_markdown(form.data, 'file', file_path)
        commit_to_git(form.data, markdown_path, 'file')
        return redirect(url_for('main.index'))
    return render_template('share_code_file.html', form=form)

@main.route('/share_blog_post', methods=['GET', 'POST'])
def share_blog_post():
    form = BlogPostForm()
    if form.validate_on_submit():
        markdown_path = create_markdown(form.data, 'blog')
        commit_to_git(form.data, markdown_path, 'blog')
        return redirect(url_for('main.index'))
    return render_template('share_blog_post.html', form=form)

@main.route('/search_code', methods=['GET', 'POST'])
def search_code():
    # You need to implement the code search functionality
    return render_template('search_code.html')

@main.route('/search_results', methods=['POST'])
def search_results():
    query = request.form['query']
    matches = search_matching_files(query)
    
    return render_template('search_results.html', matches=matches)

app/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome to Cryo-Overflow</h1>
    <p>Share and search for code related to cryogenic research.</p>
{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Cryo Overflow</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
    <ul>
        <li><a href="{{ url_for('main.index') }}">Home</a></li>
        <li><a href="{{ url_for('main.share_code') }}">Share Code</a></li>
        <li><a href="{{ url_for('main.search_code') }}">Search Code</a></li>
    </ul>
    {% block content %}
    {% endblock %}
</body>
</html>

app/templates/search_code.html
{% extends "layout.html" %}
{% block content %}
    <h1>Search for Code</h1>
    <form action="{{ url_for('main.search_results') }}" method="POST">
        <input type="text" name="query" placeholder="Enter search term..." required>
        <input type="submit" value="Search">
    </form>
{% endblock %}

app/templates/search_results.html
{% extends "layout.html" %}
{% block content %}
    <h1>Search Results</h1>
    {% if matches %}
        <ul>
            {% for match in matches %}
            <h2><a href="{{ match.file_link }}">{{ match.filename }}</a></h2>
            <pre>{{ match.context|join }}</pre>
            {% endfor %}
        </ul>
    {% else %}
        <p>No results found.</p>
    {% endif %}
{% endblock %}

app/templates/share_blog_post.html
{% extends "layout.html" %}
{% block content %}
    <h1>Share Blog Post</h1>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <label for="title">Title</label>
        {{ form.title(size=30) }}<br>
        <label for="post">Post:</label>
        {{ form.post(size=600) }}<br>
        <input type="submit" value="Share">
    </form>
{% endblock %}

app/templates/share_code.html
{% extends "layout.html" %}
{% block content %}
    <h1>Share Your Code</h1>
    <ul>
        <li><a href="{{ url_for('main.share_code_snippet') }}">Share Code Snippet</a></li>
        <li><a href="{{ url_for('main.share_code_file') }}">Share Code File</a></li>
        <li><a href="{{ url_for('main.share_blog_post') }}">Share Blog Post</a></li>
    </ul>
{% endblock %}

app/templates/share_code_file.html
{% extends "layout.html" %}
{% block content %}
    <h1>Share Code File</h1>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        {{ form.title.label }} {{ form.title() }}<br>
        {{ form.file.label }} {{ form.file() }}<br>
        {{ form.description.label }} {{ form.description() }}<br>
        {{ form.language.label }} {{ form.language() }}<br>
        <input type="submit" value="Share">
    </form>
{% endblock %}

app/templates/share_code_snippet.html
{% extends "layout.html" %}

{% block content %}
<h2>Share a Code Snippet</h2>

<form method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}

    <label for="title">Title:</label>
    {{ form.title(size=30) }}<br>

    <label for="code">Code:</label>
    {{ form.code(size=300) }}<br>

    <label for="description">Description:</label>
    {{ form.description(size=300) }}<br>

    <label for="language">Language:</label>
    {{ form.language() }}<br>

    <input type="submit" value="Share">
</form>
{% endblock %}